# Generated by Django 2.2.28 on 2025-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0001_initial'),
    ]

    operations = [
        
    ]
