# Generated by Django 2.2.28 on 2025-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0002_auto_20250325_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default="{% static 'images/placeholder_album.jpg' %}", null=True, upload_to='albums/'),
        ),
    ]
