# Generated by Django 2.2.28 on 2025-03-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0002_auto_20250326_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
    ]
