# Generated by Django 2.2.28 on 2025-03-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0003_remove_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
