# Generated by Django 2.2.28 on 2025-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0003_auto_20250325_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default="'albums/placeholder_album.jpg'", null=True, upload_to='albums/'),
        ),
    ]
