# Generated by Django 2.2.28 on 2025-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0004_auto_20250325_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='placeholder_album.jpg', null=True, upload_to='albums/'),
        ),
    ]
