# Generated by Django 2.2.28 on 2025-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0004_remove_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='averageRating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='averageRating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
