# Generated by Django 2.2.28 on 2025-03-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0003_auto_20250319_1805'),
        ('music_notes', '0004_auto_20250320_0004'),
    ]

    operations = [
    ]
