# Generated by Django 2.2.28 on 2025-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0005_auto_20250327_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
    ]
