# Generated by Django 2.2.28 on 2025-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0006_auto_20250327_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='averageRating',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='song',
            name='averageRating',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
