# Generated by Django 2.2.28 on 2025-03-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0006_song_artist'),
        ('music_notes', '0002_auto_20250313_1037'),
    ]

    operations = [
    ]
