# Generated by Django 2.2.28 on 2025-03-26 12:19

from django.db import migrations, models
import django.db.models.deletion
import music_notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0007_merge_20250320_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=music_notes.models.Song.default_artist, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_notes.Artist'),
        ),
    ]
