# Generated by Django 2.2.28 on 2025-03-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_notes', '0007_auto_20250327_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums'),
        ),
    ]
